[build-system]
requires = ["setuptools>=61.0", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-vs30-model"
# version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{name = "Claudio Schill"}]
dynamic = ["version"]
requires-python = ">=3.13,<3.14"
dependencies = [
    "ngboost",
    "pandas",
    "numpy",
    "scipy",
    "xarray",
    "matplotlib",
    "seaborn",
    "einops",
]

[tool.setuptools_scm]
fallback_version = "v0.0.0"

[tool.setuptools.package-dir]
ml_vs30_model = "ml_vs30_model"