seed: 42
model_type: catboost


apply_vs30_sample_weights: true
max_vs30_weight: 2.5

input_variables:
  - roughness
  - topographic_slope
  - compound_topographic_index
  - geomorphon
  - profile_curvature
  - tangential_curvature
  - terrain_ruggedness_index
  - topographic_position_index
  - vector_ruggedness_measure
  - landform_shannon_index
  - landform_entropy
  - landform_uniformity
  - absolute_depth_to_bedrock
  - depth_to_groundwater
  - nz_geology_category
  - nz_distance_to_coast

n_cv_folds: 25

rel_results_dir: results