rel_vs30_values_ffp: cleaned_vs30_data/foster_2019.csv
index_col: null

drop_sites: null
drop_quality_score: null

input_variables: 
  - nz_geology_age_min
  - nz_geology_age_max
  - nzenvds_slope_deg
  - nzenvds_topo_roughness
derived_variables:
  - nz_geology_age_mid
  - nz_geology_age_ln_mid




