rel_vs30_values_ffp: cleaned_vs30_data/nzgmdb_site_table_Q1Q2Q3.csv
index_col: "sta"

apply_vs30_weighting: true
max_vs30_weight: 5

total_max_weight: 10

input_variables: 
  - roughness
  - topographic_slope
  - compound_topographic_index
  - geomorphon
  - profile_curvature
  - tangential_curvature
  - terrain_ruggedness_index
  - topographic_position_index
  - vector_ruggedness_measure
  - landform_shannon_index
  - landform_entropy
  - landform_uniformity
  - absolute_depth_to_bedrock
  - depth_to_groundwater
  - nz_geology_category


