rel_vs30_values_ffp: cleaned_vs30_data/nz_combined.csv
index_col: "sta"

drop_sites: 
  # Loacted on Whakaari/White Island, most input variables are 
  # garbage for this site.
  - WSRZ 
  # Duplicates
  - 029A  # Same as HCDS
  - 928B  # Same as HNPS
  - 014A  # Same as NCDS
  - 096A  # Same as 225B
  - 709A  # Same as GWTS
  - 017A  # Same as GISS
  - 249A  # Same as 642H
  - 642G  # Same as 642H
  - 646A  # Same as 646C
  - D10C  # Same as CCPS
  - 044A  # Same as SKFS

drop_quality_score: null

input_variables: 
  # - roughness
  # - topographic_slope
  - compound_topographic_index
  # - geomorphon
  - profile_curvature
  - tangential_curvature
  - terrain_ruggedness_index
  - topographic_position_index
  - vector_ruggedness_measure
  - landform_shannon_index
  - landform_entropy
  - landform_uniformity
  - absolute_depth_to_bedrock
  - depth_to_groundwater
  - elevation
  - nz_lithology_category
  - nz_geological_unit
  - nz_main_rock
  - nz_quaternary_region
  - nz_geology_category
  - nz_distance_to_coast
  - nz_distance_to_river_st1
  - nz_distance_to_river_st2
  - nz_distance_to_river_st3
  - nz_distance_to_river_st4
  - nz_distance_to_river_st5
  - nz_distance_to_river_st6
  - nz_distance_to_river_st7
  - nz_distance_to_river_st8
  - nz_distance_to_river_st1_greater
  - nz_distance_to_river_st2_greater
  - nz_distance_to_river_st3_greater
  - nz_distance_to_river_st4_greater
  - nz_distance_to_river_st5_greater
  - nz_distance_to_river_st6_greater
  - nz_distance_to_river_st7_greater
  - nz_geology_age_min
  - nz_geology_age_max
  - nz_nlm_groundwater_depth
  - nz_nwt_groundwater_depth
  - nzenvds_distance_rivers
  - nzenvds_distance_rivers_vertical
  - nzenvds_precip_ann
  - nzenvds_slope_deg
  - nzenvds_soil_acid_p
  - nzenvds_soil_age
  - nzenvds_soil_drainage
  - nzenvds_soil_induration
  - nzenvds_soil_particle_size
  - nzenvds_topo_geomorphons
  - nzenvds_topo_normalised_height
  - nzenvds_topo_position
  - nzenvds_topo_roughness
  - nzenvds_topo_ruggedness
  - nzenvds_topo_valley_depth
  - nzenvds_topo_wetness
derived_variables:
  - nz_geology_age_mid
  - nz_geology_age_ln_mid
  - nz_combined_groundwater_depth
  - nz_combined_groundwater_depth_ln
  - mainrock_proxy



