rel_vs30_values_ffp: cleaned_vs30_data/nz_site_db_v1p5.csv
index_col: "sta"

input_variables: 
  # - roughness
  # - topographic_slope
  - compound_topographic_index
  # - geomorphon
  - profile_curvature
  - tangential_curvature
  - terrain_ruggedness_index
  - topographic_position_index
  - vector_ruggedness_measure
  - landform_shannon_index
  - landform_entropy
  - landform_uniformity
  - absolute_depth_to_bedrock
  - depth_to_groundwater
  - elevation
  - nz_lithology_category
  - nz_geological_unit
  # - nz_geology_category
  - nz_distance_to_coast
  - nz_geology_age_min
  - nz_geology_age_max
  - nz_nlm_groundwater_depth
  - nz_nwt_groundwater_depth
  - nzenvds_distance_rivers
  - nzenvds_distance_rivers_vertical
  - nzenvds_precip_ann
  - nzenvds_slope_deg
  - nzenvds_soil_acid_p
  - nzenvds_soil_age
  - nzenvds_soil_drainage
  - nzenvds_soil_induration
  - nzenvds_soil_particle_size
  - nzenvds_topo_geomorphons
  - nzenvds_topo_normalised_height
  - nzenvds_topo_position
  - nzenvds_topo_roughness
  - nzenvds_topo_ruggedness
  - nzenvds_topo_valley_depth
  - nzenvds_topo_wetness
derived_variables:
  - nz_geology_age_mid
  - nz_geology_age_ln_mid
  - nz_combined_groundwater_depth
  - nz_combined_groundwater_depth_ln



