# US dataset based on Geyin & Maurer dataset
rel_vs30_values_ffp: cleaned_vs30_data/geyin_maurer_vs30.csv
index_col: null

input_variables: 
  - roughness
  - topographic_slope
  - compound_topographic_index
  - geomorphon
  - profile_curvature
  - tangential_curvature
  - terrain_ruggedness_index
  - topographic_position_index
  - vector_ruggedness_measure
  - landform_shannon_index
  - landform_entropy
  - landform_uniformity
  - absolute_depth_to_bedrock
  - depth_to_groundwater


