model_type: ngboost

rel_dataset_ffp: datasets/geyin_maurer_dataset.parquet
input_variables:
  - roughness
  - topographic_slope
  - compound_topographic_index
  - geomorphon
  - profile_curvature
  - tangential_curvature
  - terrain_ruggedness_index
  - topographic_position_index
  - vector_ruggedness_measure
  - landform_shannon_index
  - landform_entropy
  - landform_uniformity
  - absolute_depth_to_bedrock
  - depth_to_groundwater


n_cv_folds: 5
